Fix OPenHab startup failure:
[ERROR] [xbase.resource.BatchLinkableResource] - resolution of uriFragment '|::0.2.4.2.0.1.1.0.0::0::/2' failed.
java.lang.UnsupportedOperationException: Missing type computation for expression type: QuantityLiteral /